events { 
    worker_connections 1024; 
}

http {
    upstream user_service {
        server user-service:5000;
    }

    upstream order_service {
        server order-service:3000;
    }

    server {
        listen 80;

        location /api/users {
            proxy_pass http://user_service;
        }

        location /api/orders {
            proxy_pass http://order_service;
        }

        location /health {
            return 200 'OK';
        }
    }
}